#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : faas-cli
Version  : 0.14.11
Release  : 57
URL      : https://github.com/openfaas/faas-cli/archive/0.14.11/faas-cli-0.14.11.tar.gz
Source0  : https://github.com/openfaas/faas-cli/archive/0.14.11/faas-cli-0.14.11.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause MIT
Requires: faas-cli-bin = %{version}-%{release}
Requires: faas-cli-license = %{version}-%{release}
BuildRequires : buildreq-golang
BuildRequires : pypi(requests)

%description
## faas-cli
[![Build Status](https://github.com/openfaas/faas-cli/workflows/build/badge.svg?branch=master)](https://github.com/openfaas/faas-cli/actions)
[![Go Report Card](https://goreportcard.com/badge/github.com/openfaas/faas-cli)](https://goreportcard.com/report/github.com/openfaas/faas-cli)
[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)
[![OpenFaaS](https://img.shields.io/badge/openfaas-serverless-blue.svg)](https://www.openfaas.com)

%package bin
Summary: bin components for the faas-cli package.
Group: Binaries
Requires: faas-cli-license = %{version}-%{release}

%description bin
bin components for the faas-cli package.


%package license
Summary: license components for the faas-cli package.
Group: Default

%description license
license components for the faas-cli package.


%prep
%setup -q -n faas-cli-0.14.11
cd %{_builddir}/faas-cli-0.14.11

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1666732093
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
make  %{?_smp_mflags}  || go build -v -mod=vendor -ldflags='-X github.com/openfaas/faas-cli/version.Version=%{version}' -o ./faas-cli -buildmode=pie


%install
export SOURCE_DATE_EPOCH=1666732093
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/faas-cli
cp %{_builddir}/faas-cli-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/faas-cli/ce62120d32a64c44b0e61ee13b9b5fd2c0cea2a1
cp %{_builddir}/faas-cli-%{version}/vendor/github.com/Azure/go-ansiterm/LICENSE %{buildroot}/usr/share/package-licenses/faas-cli/836ef1b46953afdb78ce3929bc6831ca83620b65
cp %{_builddir}/faas-cli-%{version}/vendor/github.com/VividCortex/ewma/LICENSE %{buildroot}/usr/share/package-licenses/faas-cli/5fcf3d8a80be9b86a2c442ab938090611e6ee317
cp %{_builddir}/faas-cli-%{version}/vendor/github.com/alexellis/arkade/LICENSE %{buildroot}/usr/share/package-licenses/faas-cli/3dbdeb041ef56b91e6c094423ab0c23b1dba025f
cp %{_builddir}/faas-cli-%{version}/vendor/github.com/alexellis/go-execute/LICENSE %{buildroot}/usr/share/package-licenses/faas-cli/d85cff4a6cc09e9e3feb490e39a489a5628a36f7
cp %{_builddir}/faas-cli-%{version}/vendor/github.com/alexellis/hmac/LICENSE %{buildroot}/usr/share/package-licenses/faas-cli/f1ae47fecc13bcdc9beb6dc74be71d0fd4e34bbd
cp %{_builddir}/faas-cli-%{version}/vendor/github.com/cheggaaa/pb/v3/LICENSE %{buildroot}/usr/share/package-licenses/faas-cli/f6beca1e369881c362566f026ea1ae521a02c98a
cp %{_builddir}/faas-cli-%{version}/vendor/github.com/docker/docker/LICENSE %{buildroot}/usr/share/package-licenses/faas-cli/20b06a68cf65738d43afa04acce0126f341c77f8
cp %{_builddir}/faas-cli-%{version}/vendor/github.com/docker/docker/NOTICE %{buildroot}/usr/share/package-licenses/faas-cli/5476f2f91673ef040f1956907e7f45e72d5e11ee
cp %{_builddir}/faas-cli-%{version}/vendor/github.com/drone/envsubst/LICENSE %{buildroot}/usr/share/package-licenses/faas-cli/572256a27f3a290c6c908d8259769ee9793f287e
cp %{_builddir}/faas-cli-%{version}/vendor/github.com/fatih/color/LICENSE.md %{buildroot}/usr/share/package-licenses/faas-cli/563519fec7769aaec054ee06cb429f39f0fdab89
cp %{_builddir}/faas-cli-%{version}/vendor/github.com/google/go-cmp/LICENSE %{buildroot}/usr/share/package-licenses/faas-cli/7080652cc78cd9855d39e324529a3b5f3745dcd6
cp %{_builddir}/faas-cli-%{version}/vendor/github.com/inconshreveable/mousetrap/LICENSE %{buildroot}/usr/share/package-licenses/faas-cli/62446e71c226403f1a2e67d0f66ede03e3fbdd2f
cp %{_builddir}/faas-cli-%{version}/vendor/github.com/mattn/go-colorable/LICENSE %{buildroot}/usr/share/package-licenses/faas-cli/5ca808f075931c5322193d4afd5a3370c824f810
cp %{_builddir}/faas-cli-%{version}/vendor/github.com/mattn/go-isatty/LICENSE %{buildroot}/usr/share/package-licenses/faas-cli/5b53018d7f0706e49275a92d36b54cfbfbb71367
cp %{_builddir}/faas-cli-%{version}/vendor/github.com/mattn/go-runewidth/LICENSE %{buildroot}/usr/share/package-licenses/faas-cli/5ca808f075931c5322193d4afd5a3370c824f810
cp %{_builddir}/faas-cli-%{version}/vendor/github.com/mitchellh/go-homedir/LICENSE %{buildroot}/usr/share/package-licenses/faas-cli/5ad2002bc8d2b22e2034867d159f71ba6258e18f
cp %{_builddir}/faas-cli-%{version}/vendor/github.com/moby/term/LICENSE %{buildroot}/usr/share/package-licenses/faas-cli/20b06a68cf65738d43afa04acce0126f341c77f8
cp %{_builddir}/faas-cli-%{version}/vendor/github.com/morikuni/aec/LICENSE %{buildroot}/usr/share/package-licenses/faas-cli/3faf341fbc32621fe1ac089ae2ab7a23980fc189
cp %{_builddir}/faas-cli-%{version}/vendor/github.com/olekukonko/tablewriter/LICENSE.md %{buildroot}/usr/share/package-licenses/faas-cli/7c15369a8295c6d2cd26b41618f5ba81e7e06eca
cp %{_builddir}/faas-cli-%{version}/vendor/github.com/openfaas/faas-provider/LICENSE %{buildroot}/usr/share/package-licenses/faas-cli/f1ae47fecc13bcdc9beb6dc74be71d0fd4e34bbd
cp %{_builddir}/faas-cli-%{version}/vendor/github.com/openfaas/faas/gateway/LICENSE %{buildroot}/usr/share/package-licenses/faas-cli/fc3fc032d02290b035bbf80a8a085da61cf75c3f
cp %{_builddir}/faas-cli-%{version}/vendor/github.com/pkg/errors/LICENSE %{buildroot}/usr/share/package-licenses/faas-cli/9c1bedc0d42f24c24a1bd266f3ce101a4b0579fc
cp %{_builddir}/faas-cli-%{version}/vendor/github.com/rivo/uniseg/LICENSE.txt %{buildroot}/usr/share/package-licenses/faas-cli/f60d047cd34de4c91b3a045ebf117fe54b3c279e
cp %{_builddir}/faas-cli-%{version}/vendor/github.com/ryanuber/go-glob/LICENSE %{buildroot}/usr/share/package-licenses/faas-cli/f25ad3680192d554da0315f90fa71f63278a5326
cp %{_builddir}/faas-cli-%{version}/vendor/github.com/spf13/cobra/LICENSE.txt %{buildroot}/usr/share/package-licenses/faas-cli/c7feacb4667f8c63c89e2eeeb9a913bd3ced8ac2
cp %{_builddir}/faas-cli-%{version}/vendor/github.com/spf13/pflag/LICENSE %{buildroot}/usr/share/package-licenses/faas-cli/b3c86ae465b21f7323059db335158b48187731c7
cp %{_builddir}/faas-cli-%{version}/vendor/golang.org/x/sys/LICENSE %{buildroot}/usr/share/package-licenses/faas-cli/d6a5f1ecaedd723c325a2063375b3517e808a2b5
cp %{_builddir}/faas-cli-%{version}/vendor/gopkg.in/yaml.v2/LICENSE %{buildroot}/usr/share/package-licenses/faas-cli/92170cdc034b2ff819323ff670d3b7266c8bffcd
cp %{_builddir}/faas-cli-%{version}/vendor/gopkg.in/yaml.v2/LICENSE.libyaml %{buildroot}/usr/share/package-licenses/faas-cli/ad00ce7340d89dc13ccc59920ef75cb55af5b164
cp %{_builddir}/faas-cli-%{version}/vendor/gopkg.in/yaml.v2/NOTICE %{buildroot}/usr/share/package-licenses/faas-cli/9522d95b2b9b284285cc3fb6ecc445aa3ee5e785
true
## install_append content
install -d %{buildroot}/usr/bin
install -p -m 755 ./faas-cli %{buildroot}/usr/bin/faas-cli
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/faas-cli

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/faas-cli/20b06a68cf65738d43afa04acce0126f341c77f8
/usr/share/package-licenses/faas-cli/3dbdeb041ef56b91e6c094423ab0c23b1dba025f
/usr/share/package-licenses/faas-cli/3faf341fbc32621fe1ac089ae2ab7a23980fc189
/usr/share/package-licenses/faas-cli/5476f2f91673ef040f1956907e7f45e72d5e11ee
/usr/share/package-licenses/faas-cli/563519fec7769aaec054ee06cb429f39f0fdab89
/usr/share/package-licenses/faas-cli/572256a27f3a290c6c908d8259769ee9793f287e
/usr/share/package-licenses/faas-cli/5ad2002bc8d2b22e2034867d159f71ba6258e18f
/usr/share/package-licenses/faas-cli/5b53018d7f0706e49275a92d36b54cfbfbb71367
/usr/share/package-licenses/faas-cli/5ca808f075931c5322193d4afd5a3370c824f810
/usr/share/package-licenses/faas-cli/5fcf3d8a80be9b86a2c442ab938090611e6ee317
/usr/share/package-licenses/faas-cli/62446e71c226403f1a2e67d0f66ede03e3fbdd2f
/usr/share/package-licenses/faas-cli/7080652cc78cd9855d39e324529a3b5f3745dcd6
/usr/share/package-licenses/faas-cli/7c15369a8295c6d2cd26b41618f5ba81e7e06eca
/usr/share/package-licenses/faas-cli/836ef1b46953afdb78ce3929bc6831ca83620b65
/usr/share/package-licenses/faas-cli/92170cdc034b2ff819323ff670d3b7266c8bffcd
/usr/share/package-licenses/faas-cli/9522d95b2b9b284285cc3fb6ecc445aa3ee5e785
/usr/share/package-licenses/faas-cli/9c1bedc0d42f24c24a1bd266f3ce101a4b0579fc
/usr/share/package-licenses/faas-cli/ad00ce7340d89dc13ccc59920ef75cb55af5b164
/usr/share/package-licenses/faas-cli/b3c86ae465b21f7323059db335158b48187731c7
/usr/share/package-licenses/faas-cli/c7feacb4667f8c63c89e2eeeb9a913bd3ced8ac2
/usr/share/package-licenses/faas-cli/ce62120d32a64c44b0e61ee13b9b5fd2c0cea2a1
/usr/share/package-licenses/faas-cli/d6a5f1ecaedd723c325a2063375b3517e808a2b5
/usr/share/package-licenses/faas-cli/d85cff4a6cc09e9e3feb490e39a489a5628a36f7
/usr/share/package-licenses/faas-cli/f1ae47fecc13bcdc9beb6dc74be71d0fd4e34bbd
/usr/share/package-licenses/faas-cli/f25ad3680192d554da0315f90fa71f63278a5326
/usr/share/package-licenses/faas-cli/f60d047cd34de4c91b3a045ebf117fe54b3c279e
/usr/share/package-licenses/faas-cli/f6beca1e369881c362566f026ea1ae521a02c98a
/usr/share/package-licenses/faas-cli/fc3fc032d02290b035bbf80a8a085da61cf75c3f
